### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by pritam047** [pikaz143/MenuManagement#1]
in upload.js,data should be added to the database as array of objects.
Example
Veg:[ { item : Paneer Jalfrezi , price : rs.120 } ,{ item : Malai kofta , price : rs.150 } ]

Should be somewhat similar to this:     
![s01](https://user-images.githubusercontent.com/42296778/66594778-68b8e100-ebb7-11e9-884e-473b3d81d6da.jpg)

below is the complete format
![s02](https://user-images.githubusercontent.com/42296778/66595016-bf261f80-ebb7-11e9-9e66-272f46dc8d7a.jpg)
But all the items should be filled as array of objects.

**Comment by rmasianjr** [comment]
Hi. i want to help :relaxed:
im working on this now..

**Comment by pritam047** [comment]
@rmasianjr Good Work. 👍
